import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div className="min-h-screen w-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-black">
        <h1 className="text-3xl text-white font-bold underline">
          Hello world!
        </h1>
      </main>
    </div>
  );
};

export default Home;
